[window]
title      = 'Zippy!'
width      = 900
height     = 700
fullscreen = true
flags      = 2 # OpenGL

[level]
width      = 900
height     = 700


[inputs]
mouse      = true
keyboard   = true
controller = false
window     = true
file-drop  = false

[brick]
width  = 15
height = 15

[ball]
radius  = 7

[paddle]
width  = 100
height = 7
speed  = 7
